FROM python:3.8-slim
#RUN groupadd -r django && useradd --no-log-init -r -g django django
#USER django:django
WORKDIR /app
#WORKDIR /home/django/app
COPY requirements.txt .
RUN pip install --user -r requirements.txt
COPY . .
EXPOSE 8000
RUN python3 manage.py collectstatic --noinput
CMD ["python3","-m","gunicorn", "--reload", "-b","[::]:8000","testDjango.wsgi:application"]
